# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-24 16:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20170118_0308'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_name', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('line1', models.TextField(max_length=200)),
                ('guide_number', models.CharField(max_length=50, null=True)),
                ('postal_code', models.CharField(max_length=50)),
                ('country_code', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('status', models.CharField(default='creado', max_length=50)),
                ('total', models.DecimalField(decimal_places=2, max_digits=9)),
                ('shopping_cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.ShoppingCart')),
            ],
        ),
    ]
